ETHZ-TEC/RocketLogger

- script/python/setup.py
> Specify version of required Python package dependencies

- software/node_server/static/js/rl.control.js
* replace filename extension on change of the data format in the web interface
* add filename extension if filename edits do not include format specific extension
Fixes: #49
> Fix filename extension update in web interface

- software/rocketlogger/rl_file.c
> fix aggregation issue due to 32-bit overflow

- script/python/MANIFEST.in
- script/python/docs/data.rst
* fix package manifest to include proper sample scripts
* update documentation of samples scripts provided in source distribution
Fixes: #33
> Fix python packaging configuration

- script/python/MANIFEST.in
- script/python/docs/index.rst
- script/python/docs/rocketlogger.rst
- script/python/docs/tests.rst
- script/python/tests/test_calibration.py
* fix test related regressions from #41
* update test documentation
Relates to: #40 #41
> Fix Python package test regressions

- script/python/rocketlogger/data.py
- script/python/tests/test_data.py
- software/rocketlogger/pru.c
* fixes channel info data allocation for split file header
* update Python library support for split files
* more strict cross validation of split measurement file headers
* tolerate corrupt channel info header for split file imports (enable import of files affected by #62)
Fixes: #62
> Fix channel info header of split files

- CHANGELOG.md
- script/python/LICENSE
- script/python/README.md
- script/python/bug57_recover.py
- script/python/docs/conf.py
- script/python/docs/index.rst
- script/python/rocketlogger/data.py
- script/python/setup.py
- script/python/tests/test_data.py
- software/node_server/package-lock.json
- software/node_server/package.json
- software/rocketlogger/Doxyfile
- software/rocketlogger/meson.build
- software/rocketlogger/pru.c
- software/rocketlogger/rl_file.c
- software/system/setup/system/issue.net
Pull request to track changes and release related tasks for RocketLogger version 2.0.2.
**Release Checklist**
> Release 2.0.2

- software/node_server/package-lock.json
- software/node_server/package.json
- software/node_server/templates/base.html
- software/node_server/templates/control.html
Review web interface dependency specification and update dependencies to latest version. Fixes several security related issues in dependencies.
Fixes: #69
> Update web interface dependencies

- software/node_server/.eslintrc.js
- software/node_server/.gitignore
- software/node_server/jest.config.js
- software/node_server/package-lock.json
- software/node_server/package.json
* add ESLint as development dependency with basic configuration
* add Jest testing framework as development dependency with configuration for ES module testing
> JavaScript development and testing tools

- software/rocketlogger/tests/.gitignore
- software/rocketlogger/tests/README.md
- software/rocketlogger/tests/requirements.txt
- software/rocketlogger/tests/rocketlogger_cli.py
- software/rocketlogger/tests/test_sample_process.py
- software/system/setup/setup.sh
* Introduce system tests for various sampling configurations, including data file import using Python support library
* Include installation of required Python system packages in the image setup scripts for generating the required Python environment
> RocketLogger and Python support library system tests

- software/node_server/app.js
- software/node_server/rl.control.js
- software/node_server/rl.data.js
- software/node_server/rl.files.js
* extract data and status update handling to dedicated Subscriber classes
* properly filter measurement filename for web interface status messages
> Refactor measurement data and status update subscription

- software/system/get_image.sh
* update to latest Debian buster console image
> Update Debian base system image

- .github/workflows/python-package.yml
- script/python/README.md
- script/python/setup.py
- script/python/tox.ini
* add support for Python 3.11
* extend tox test coverage
> Add Python 3.11 support

- README.md
- software/node_server/README.md
- software/node_server/package-lock.json
- software/system/setup/setup.sh
* upgrade to Node.js version 18
* upgrade package-lock.json file version
> Upgrade Node.js to version 18 LTS

- script/python/rocketlogger/calibration.py
- script/python/tests/test_calibration.py
Improve compatibility for processing calibration measurements with only a few set-points
* reduce initial set-point detection step size
* extend set-point detection error handling
Relates to: #80
> Improve calibration set-point detection

- rocketlogger.code-workspace
- software/node_server/.vscode/launch.json
* update VS Code plugin recommendations for meson and systemd
* add Jest plugin for VS Code
* minor VS Code config fixes
> Update development tools configuration

- .gitlab-ci.yml
- software/node_server/jest.config.js
- software/node_server/package-lock.json
- software/node_server/package.json
- software/rocketlogger/Dockerfile
* software build using ARM Docker image
* Python support library testing & reporting
* Javascript testing & reporting
* add Jest test reporting plugin to web server development dependencies
> GitLab CI configuration

- software/node_server/rl.data.js
* resolves ambient measurement preview not shown for samples rates >1 kSps
> Fix server side resampling of high data rate measurements

- software/node_server/buffer.js
- software/node_server/rl.cache.js
- software/node_server/static/js/rl.data.js
- software/node_server/tests/buffer.test.js
* improved aggregating buffer capacity tracking and cache readout
* fix cached data handling for low rate data (ambient measurements)
* review and cleanup aggregating buffer tests
> Measurement buffer and cache optimizations

- CHANGELOG.md
- script/python/docs/conf.py
- script/python/setup.py
- software/node_server/package-lock.json
- software/node_server/package.json
- software/node_server/templates/control.html
- software/rocketlogger/Doxyfile
- software/rocketlogger/meson.build
- software/rocketlogger/tests/README.md
- software/system/get_image.sh
- software/system/setup/system/issue.net
Pull request to track changes and release related tasks for RocketLogger version 2.1.1.
**Release Checklist**
> Release 2.1.1

- .gitlab-ci.yml
- script/python/docs/conf.py
- software/rocketlogger/Doxyfile
- software/rocketlogger/README.md
- software/rocketlogger/calibration.h
- software/rocketlogger/config/README.md
- software/rocketlogger/gpio.h
- software/rocketlogger/overlay/README.md
- software/rocketlogger/pru.h
- software/rocketlogger/rl_file.c
- software/rocketlogger/sensor/bme280.c
- software/rocketlogger/sensor/tsl4531.c
- software/rocketlogger/util.h
* add GitLab CI job for doxygen software documentation
* add GitLab CI job for Python Sphinx documentation
* update and fix documentation configurations
* fix documentation warnings
Relates to: #105
> GitLab CI jobs for documentation checks

- .github/workflows/publish-docs.yml
- script/python/docs/conf.py
* fix GitHub action for publishing Python release documentation
* fix documentation configurations
Fixes: #105
> Fix Python release documentation generation
